# Generated by Django 6.0.5 on 2026-05-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_name_alter_subscription_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymmembership',
            old_name='subscription',
            new_name='subsrciption',
        ),
    ]
