# Generated by Django 6.0.5 on 2026-05-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_subscription_gymmembership_subsrciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmembership',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
